#+TITLE: Abstract: Deep-Learning-based Image Denoising in Ophthalmology
#+LaTeX_CLASS_OPTIONS: [a4paper, 12pt]
#+OPTIONS: date:nil toc:nil
#+LATEX_HEADER: %\renewcommand\maketitle{}

Intraoperative medical imaging is an important part of modern surgery.
This project is focussed mostly on the example of retinal membrane peeling, which is an ophthalmic operation.
While high quality images are available in the diagnostic phase, this is not true during operations.

During ophthalmic procedures, the surgeon manipulates anatomical structures of the retina with micron-scale maneuvers while observing the scene indirectly via microscope.
The resulting magnification has the effect that only a small area is focussed, other parts are either distorted or occluded.
Additionally, the motion of the eye introduces blur.
All these factors result in images which are corrupted by noise.
This makes precise operations more difficult.
The intraoperative images not only differ from the diagnostic ones in terms of quality.
During surgery, instruments are present and the membrane is stained with a coloring agent to amplify its edges.

Image processing algorithms can be used to increase the quality of the images via upscaling and denoising.
An image restoration algorithm has to fulfil the following requirements to be considered useful in an intraoperative setting:
\begin{enumerate}
\item All processing should happen in real time.
\item It has to work with images of varying quality, level of zoom and different positions of surgical instruments.
\item The anatomical structure, the position of surgical instruments, and the color have to be conserved.
Both blood vessels and the border of the membrane should be at least as clearly visible as in the original images.
This implies that we have to preserve the image edges.
\end{enumerate}
All mentioned requirements are not specific to the application to ophthalmic surgery but also apply in the more general case.

A denoising tool could also be used as a pre-processing step for further image processing procedures.
Examples for this are automatic vessel segmentation and image registration, which both require high-quality images.

The performance of classical image denoising algorithms is not promising for this scenario, because the nature of the image corruption is both complicated and highly irregular.
This is why this project is focused on deep learning methods, which have been successfully used for both super-resolution and image restoration problems.

We will use a dataset consisting of diagnostic retinal fundus images.
They have a high quality and thus do not correspond to realistic intraoperative conditions.
To rectify this, we have to perform data augmentation, i.e., we need to corrupt the images artificially and need to modify their content, for example by adding surgical tools.

Because the anatomical structure of the retina is similar in both intraoperative and diagnostic images, we hope that transfer learning will provide good results.
This means that we can use a large set of readily-available images for the initial training procedure.
After this is done, the algorithm can be fine-tuned with a small dataset for which a ground truth is available.
This is a promising approach in our case as both datasets consist of images with a similar structure.

During the last few years a vast amount of different neural network topologies has been published.
Most of them work on a larger amount of data than we have available and are complex models that do not work in real-time.
The goal of this guided research is to compare different approaches for the denoising and upscaling of the aforementioned pictures.
The main challenge of this project is finding a good trade-off between the resulting image quality and the usability during surgery.
